name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Debug environment
      run: |
        pwd
        ls -la
        echo "Node version: $(node -v)"
        echo "NPM version: $(npm -v)"

    - name: Clean previous installations
      run: |
        rm -rf ~/.conde
        rm -rf /tmp/test-env

    - name: Prepare test environment
      run: |
        chmod +x scripts/install.sh
        chmod +x scripts/test/test_install.sh
        # Debug permisos
        ls -la scripts/
        ls -la scripts/test/

    - name: Run install script tests
      run: |
        # Debug instalación
        echo "Running install script..."
        bash ./scripts/test/test_install.sh
        echo "Install script completed"
        ls -la ~/.conde/

    - name: Clean for next tests
      run: |
        rm -rf ~/.conde/envs/*
        rm -rf ~/.conde/packages/*

    - name: Install dependencies
      run: |
        cd ~/.conde
        # Debug dependencias
        echo "Installing dependencies in $(pwd)..."
        ls -la
        npm install --production --verbose
        ls -la node_modules/

    - name: Setup shell environment
      run: |
        echo "Setting up shell environment..."
        CONDE_ROOT="$HOME/.conde"
        echo "CONDE_ROOT=$CONDE_ROOT" >> $GITHUB_ENV
        echo "CONDE_BIN=$CONDE_ROOT/bin" >> $GITHUB_ENV
        echo "CONDE_ENVS=$CONDE_ROOT/envs" >> $GITHUB_ENV
        echo "CONDE_PACKAGES=$CONDE_ROOT/packages" >> $GITHUB_ENV
        echo "CONDE_LIB=$CONDE_ROOT/lib" >> $GITHUB_ENV
        echo "$CONDE_ROOT/bin" >> $GITHUB_PATH
        
        # Debug variables
        echo "Configured variables:"
        echo "CONDE_ROOT: $CONDE_ROOT"
        echo "CONDE_BIN: $CONDE_ROOT/bin"
        echo "CONDE_ENVS: $CONDE_ROOT/envs"
        echo "PATH addition: $CONDE_ROOT/bin"

    - name: Test environment creation
      shell: bash
      env:
        CONDE_ROOT: ${{ env.CONDE_ROOT }}
        CONDE_BIN: ${{ env.CONDE_BIN }}
        CONDE_ENVS: ${{ env.CONDE_ENVS }}
        CONDE_PACKAGES: ${{ env.CONDE_PACKAGES }}
        CONDE_LIB: ${{ env.CONDE_LIB }}
      run: |
        # Crear script temporal con todo el contexto
        cat > /tmp/test-script.sh << 'EOF'
        #!/bin/bash
        set -e
        
        # Setup environment
        export CONDE_ROOT="$HOME/.conde"
        export CONDE_BIN="$CONDE_ROOT/bin"
        export CONDE_ENVS="$CONDE_ROOT/envs"
        export CONDE_PACKAGES="$CONDE_ROOT/packages"
        export CONDE_LIB="$CONDE_ROOT/lib"
        export PATH="$CONDE_ROOT/bin:$PATH"
        
        # Source conde
        source ~/.conde/scripts/conde.sh
        
        # Create environment
        echo "Creating test environment..."
        conde create test-env --node 20.5.0
        
        # Activate environment
        echo "Activating test environment..."
        conde activate test-env
        
        # Install package
        cd /tmp
        echo '{"dependencies": {"express": "^4.17.1"}}' > package.json
        conde install express
        
        # Verify installation
        which node
        node -v
        npm -v
        conde list envs
        conde list packages
        EOF
        
        # Make script executable and run it
        chmod +x /tmp/test-script.sh
        bash /tmp/test-script.sh