name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Prepare test environment
      run: |
        chmod +x scripts/install.sh
        chmod +x scripts/test/test_install.sh

    - name: Run install script tests
      run: ./scripts/test/test_install.sh

    - name: Install dependencies
      run: |
        cd ~/.conde
        npm install --production

    - name: Test environment creation
      run: |
        source ~/.conde/scripts/conde.sh
        # Verificar que conde está disponible
        which conde || echo "conde not found in PATH"
        echo "Current PATH: $PATH"
        # Crear y activar entorno
        conde create test-env --node 20.5.0
        conde activate test-env
        # Instalar un paquete de prueba
        cd /tmp  # Cambiar a un directorio neutral
        echo '{"dependencies": {"express": "^4.17.1"}}' > package.json
        conde install express
        # Verificar la instalación
        which node
        node -v
        npm -v
        conde list envs
        conde list packages 