name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Debug environment
      run: |
        pwd
        ls -la
        echo "Node version: $(node -v)"
        echo "NPM version: $(npm -v)"

    - name: Prepare test environment
      run: |
        chmod +x scripts/install.sh
        chmod +x scripts/test/test_install.sh
        # Debug permisos
        ls -la scripts/
        ls -la scripts/test/

    - name: Run install script tests
      run: |
        # Debug instalación
        echo "Running install script..."
        bash ./scripts/test/test_install.sh
        echo "Install script completed"
        ls -la ~/.conde/

    - name: Install dependencies
      run: |
        cd ~/.conde
        # Debug dependencias
        echo "Installing dependencies in $(pwd)..."
        ls -la
        npm install --production --verbose
        ls -la node_modules/

    - name: Setup shell environment
      run: |
        echo "Setting up shell environment..."
        echo "export CONDE_ROOT=$HOME/.conde" >> $GITHUB_ENV
        echo "export CONDE_BIN=$CONDE_ROOT/bin" >> $GITHUB_ENV
        echo "export CONDE_ENVS=$CONDE_ROOT/envs" >> $GITHUB_ENV
        echo "export CONDE_PACKAGES=$CONDE_ROOT/packages" >> $GITHUB_ENV
        echo "export CONDE_LIB=$CONDE_ROOT/lib" >> $GITHUB_ENV
        echo "$HOME/.conde/bin" >> $GITHUB_PATH
        echo "Shell environment set up"

    - name: Test environment creation
      shell: bash
      run: |
        # Debug PATH y entorno
        echo "Current PATH: $PATH"
        echo "Current directory: $(pwd)"
        echo "CONDE_ROOT: $CONDE_ROOT"
        
        # Cargar conde
        echo "Sourcing conde.sh..."
        source ~/.conde/scripts/conde.sh
        
        # Verificar conde
        echo "Checking conde command..."
        which conde || echo "conde not found"
        type conde || echo "conde function not defined"
        
        # Crear entorno
        echo "Creating test environment..."
        bash -c "source ~/.conde/scripts/conde.sh && conde create test-env --node 20.5.0"
        
        # Activar entorno
        echo "Activating test environment..."
        bash -c "source ~/.conde/scripts/conde.sh && conde activate test-env"
        
        # Verificar estado
        echo "Environment status:"
        echo "CONDE_ENV: $CONDE_ENV"
        echo "CONDE_ENV_PATH: $CONDE_ENV_PATH"
        echo "NODE_PATH: $NODE_PATH"
        
        # Instalar paquete
        cd /tmp
        echo "Creating package.json..."
        echo '{"dependencies": {"express": "^4.17.1"}}' > package.json
        cat package.json
        
        echo "Installing express..."
        bash -c "source ~/.conde/scripts/conde.sh && conde install express"
        
        # Verificar instalación
        echo "Verifying installation..."
        which node
        node -v
        npm -v
        bash -c "source ~/.conde/scripts/conde.sh && conde list envs"
        bash -c "source ~/.conde/scripts/conde.sh && conde list packages"